name: Docker tag build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build local image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
