name: Docker image build

on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/deploy-image.yml"
      - "Dockerfile"
      - "config.toml"
      - "content/**"
      - "sass/**"
      - "static/**"
      - "templates/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/deploy-image.yml"
      - "Dockerfile"
      - "config.toml"
      - "content/**"
      - "sass/**"
      - "static/**"
      - "templates/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build local image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
